{{ if eq .Values.haproxy.stats.http.enable true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "haproxy-redis.fullname" . }}-stats
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.haproxy.stats.http.port }}
    protocol: TCP
    targetPort: {{ .Values.haproxy.stats.http.port }}
  selector:
    app: {{ template "haproxy-redis.fullname" . }}
    release: "{{ .Release.Name }}"
  type: ClusterIP
{{ end }}
