apiVersion: v1
kind: ConfigMap
metadata:
  name: health-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "redis-ha.fullname" . }}
data:
  ping_readiness_local.sh: |-
    HOSTNAME="$(hostname)"
    REDIS_PORT="{{ .Values.redis.port }}"
    MASTER="$(redis-cli -h {{ template "redis-ha.fullname" . }} -p {{ .Values.sentinel.port }} sentinel get-master-addr-by-name {{ .Values.redis.masterGroupName }} | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
    set -eu

    ping_response=$(
      timeout -s 9 $1 \
      redis-cli \
{{- if .Values.auth }}
        -a "$AUTH" --no-auth-warning \
{{- end }}
        -h $HOSTNAME \
        -p $REDIS_PORT \
        ping
    )
    if [ "$ping_response" != "PONG" ]; then
      echo "$ping_response"
      exit 1
    fi

    info_response=$(
      timeout -s 9 $1 \
      redis-cli \
{{- if .Values.auth }}
        -a "$AUTH" --no-auth-warning \
{{- end }}
        -h $HOSTNAME \
        -p $REDIS_PORT \
        role
    )

    echo "$info_response"

    case "$info_response" in
      *master*)
        exit 0
        ;;
      *)
        echo ":::::::::$MASTER"
        if [ "$MASTER" ]; then
          echo "It's a initial step."
          exit 0
        else
          echo "This is a slave because It's not a initial step."
          exit 1
        fi
        ;;
    esac

  ping_liveness_local.sh: |-
    REDIS_PORT={{ .Values.redis.port }}
    HOSTNAME="$(hostname)"
    set -eu

    response=$(
      timeout -s 9 $1 \
      redis-cli \
{{- if .Values.auth }}
        -a "$AUTH" --no-auth-warning \
{{- end }}
        -h $HOSTNAME \
        -p $REDIS_PORT \
        ping
    )
    if [ "$response" != "PONG" ] && [ "$response" != "LOADING Redis is loading the dataset in memory" ]; then
      echo "$response"
      exit 1
    fi

