replicas: 2
redis:
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 512Mi

sentinel:
  quorum: 1
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 200Mi

hardAntiAffinity: false

persistentVolume:
  enabled: false

init:
  resources: {}